FROM node:20-alpine

# Установка системных пакетов и зависимостей
RUN apk add --no-cache \
  bash \
  curl \
  ffmpeg \
  python3 \
  py3-pip \
  git \
  zip \
  unzip \
  libc6-compat \
  vips-dev \
  gcc \
  g++ \
  make \
  libffi-dev \
  openssl-dev \
  jpeg-dev \
  zlib-dev \
  autoconf \
  automake \
  libtool \
  nasm

# Создание рабочей директории
WORKDIR /app

# Установка n8n через npm
RUN npm install -g n8n

# Открываем порт
EXPOSE 5678

# Запуск n8n
CMD ["n8n"]
